---
services:
  app:
    build: .
    command: ["rembg", "s", "--host", "0.0.0.0", "--port", "7000"]
    deploy:
      replicas: ${REPLICAS_COUNT:-1}
    ports:
      - ${PUBLIC_PORT:-7000:7000}
version: '3'
